version: '3.7'

services:
  # Start docker container for PostgreSQL to mock RDS
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: opendatacubepassword
    restart: always

  # Start docker container for datacube-wps
  wps:
    build: .
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  # start indexer container
  index:
     image: opendatacube/datacube-index:0.0.13
     environment:
        - DB_HOSTNAME=postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=opendatacubepassword
        - DB_DATABASE=postgres
        - DB_PORT=5432
     depends_on:
        - postgres
     entrypoint: bash -c 'sleep infinity'
