---
name: Linting

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'

env:
  ORG: opendatacube
  IMAGE: wps

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build WPS image
        run: |
          docker build --tag ${ORG}/${IMAGE}:latest .
      - name: Lint WPS image
        run: |
          docker run ${ORG}/${IMAGE}:latest /bin/sh -c "./lint-code.sh"

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install isort
      - name: isort
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: isort
          run: |
            isort --check --diff .

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bandit
        uses: tj-actions/bandit@v5
        with:
          targets: |  # or a single string "."
            test_package
          options: "-r -s B101,B104"

  pylint:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.8]
    name: Pylint
    steps:
      - name: checkout git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Install Airflow and Lint
      #   uses: s-weigand/setup-conda@v1
      #   with:
      #     update-conda: true
      #     python-version: ${{ matrix.python-version }}
      #     conda-channels: anaconda, conda-forge
      # - name: Check conda version
      #   run: conda --version
      # - name: Check python
      #   run: which python
      - name: Install airflow and run pylint
        run: |
          pip install pylint
          pylint -j 2 --reports no datacube_wps --disable=C,R,redefined-builtin,fixme,arguments-differ
