---
name: Scan

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  IMAGE_NAME: opendatacube/wps

jobs:
  cve-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull docker.io/opendatacube/wps:latest

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.2.1
        with:
          image-ref: "docker.io/opendatacube/wps:latest"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL,HIGH"

      - name: Notify Slack for Failures
        uses: rtCamp/action-slack-notify@v2.1.0
        if: failure()
        env:
          SLACK_CHANNEL: ga-wms-ops
          SLACK_ICON: "https://github.com/docker.png?size=48"
          SLACK_COLOR: "#482de1"
          SLACK_MESSAGE: ""
          SLACK_TITLE: CVE Scan alert
          SLACK_USERNAME: WPS Scanner
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
