---
name: Tests

on:
  pull_request:
    paths:
      - '**'

  push:
    paths:
      - '**'

env:
  ORG: opendatacube
  IMAGE: wps
  METADATA_CATALOG: https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/workspaces/sandbox-metadata.yaml
  PRODUCT_CATALOG: https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/workspaces/sandbox-products.csv

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Pre-pull layers
        run: docker-compose pull

      - name: Build WPS image
        run: docker-compose build

      - name: Bring up containers
        run: |
          mkdir -p ./artifacts
          chmod a+rw ./artifacts

          docker-compose up -d

      - name: Setup database caching
        uses: actions/cache@v2
        with:
          path: dump.sql
          key: sample-db-${{ github.sha }}
          restore-keys: sample-db

      - name: Populate sample database
        run: |
          touch -d $(git log -1 --pretty=%aI setup-db.sh) setup-db.sh
          ./setup-db.sh

      - name: Run test suite
        run: |
          docker-compose exec -e WPS_BASEURL=/ -T wps pytest -v --cov=./datacube_wps --cov-report=xml tests/
          docker-compose down

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./artifacts/*.xml
          fail_ci_if_error: false
